# Generated by Django 5.1.5 on 2025-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0002_historicoprecoetanol_historicoprecomilho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_milho', models.FloatField(null=True)),
                ('quantidade_art', models.FloatField(null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
