# Generated by Django 5.1.5 on 2025-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_calculoart'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculoart',
            name='volume_etanol',
            field=models.FloatField(null=True),
        ),
    ]
