# Generated by Django 5.1.5 on 2025-04-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_calculoart_volume_etanol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milho_moido', models.FloatField(null=True)),
                ('etanol_anidro_prod', models.FloatField(null=True)),
                ('etanol_hidratado_prod', models.FloatField(null=True)),
                ('ddg_produzido', models.FloatField(null=True)),
                ('renda_etanol', models.FloatField(null=True)),
                ('renda_ddg', models.FloatField(null=True)),
                ('renda_energia', models.FloatField(null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
