# Generated by Django 5.1.5 on 2025-04-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0005_dadosfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculoart',
            name='proporcao_producao',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='calculoart',
            name='rendimento_percentual',
            field=models.FloatField(null=True),
        ),
    ]
