# Generated by Django 5.1.5 on 2025-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0006_calculoart_proporcao_producao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoMoagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_milho', models.FloatField(null=True)),
                ('milho_moido', models.FloatField(null=True)),
                ('eficiencia', models.FloatField(null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
