# Generated by Django 5.1.5 on 2025-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0007_processomoagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='processomoagem',
            name='energia_total_kj',
            field=models.FloatField(null=True),
        ),
    ]
