# Generated by Django 5.1.5 on 2025-05-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0009_rename_energia_total_kj_processomoagem_energia_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquefacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amido_convertido', models.FloatField(help_text='Amido convertido (kg)', null=True)),
                ('conversao_amido', models.FloatField(help_text='Conversão do amido (%)', null=True)),
                ('tempo_liquefacao', models.FloatField(help_text='Tempo de liquefação (h)', null=True)),
                ('volume_reacao_L', models.FloatField(help_text='Volume da reação (L)', null=True)),
                ('conc_amido_inicial', models.FloatField(help_text='Concentração inicial de amido (kg/L)', null=True)),
                ('conc_amido_final', models.FloatField(help_text='Concentração final de amido (kg/L)', null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquefacao', to='simulador.processomoagem')),
            ],
        ),
    ]
