# Generated by Django 5.1.5 on 2025-05-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0010_liquefacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liquefacao',
            new_name='ProcessoLiquefacao',
        ),
    ]
