# Generated by Django 5.1.5 on 2025-05-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0012_processoliquefacao_art_gerada_curvaliquefacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoliquefacao',
            name='enzima_usada',
            field=models.FloatField(blank=True, help_text='Enzima utilizada ou necessária (g)', null=True),
        ),
    ]
