# Generated by Django 5.1.5 on 2025-03-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da cotação', unique=True)),
                ('preco_etanol', models.FloatField(help_text='Preço do etanol por litro (R$)')),
                ('preco_milho', models.FloatField(help_text='Preço do milho por saca de 60kg (R$)')),
            ],
        ),
    ]
