# Generated by Django 5.1.5 on 2025-03-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPrecoEtanol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da cotação do etanol', unique=True)),
                ('preco_etanol', models.FloatField(help_text='Preço do etanol por litro (R$)')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPrecoMilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da cotação do milho', unique=True)),
                ('preco_milho', models.FloatField(help_text='Preço do milho por saca de 60kg (R$)')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricoPreco',
        ),
    ]
