# Generated by Django 5.1.5 on 2025-05-14 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0011_rename_liquefacao_processoliquefacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoliquefacao',
            name='art_gerada',
            field=models.FloatField(help_text='Glicose fermentescível (ART) gerada (kg)', null=True),
        ),
        migrations.CreateModel(
            name='CurvaLiquefacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_h', models.FloatField(help_text='Tempo (h)')),
                ('concentracao_amido', models.FloatField(help_text='Concentração de amido (g/L)')),
                ('processo_liquefacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curva_dados', to='simulador.processoliquefacao')),
            ],
            options={
                'ordering': ['tempo_h'],
            },
        ),
    ]
