# Generated by Django 5.1.5 on 2025-05-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0013_processoliquefacao_enzima_usada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processomoagem',
            name='eficiencia',
        ),
        migrations.AddField(
            model_name='processoliquefacao',
            name='volume_agua_adicionado_L',
            field=models.FloatField(help_text='Volume de água adicionado (L)', null=True),
        ),
        migrations.AddField(
            model_name='processoliquefacao',
            name='volume_milho_L',
            field=models.FloatField(help_text='Volume estimado do milho puro (L)', null=True),
        ),
        migrations.AddField(
            model_name='processoliquefacao',
            name='volume_total_L',
            field=models.FloatField(help_text='Volume total do processo (L)', null=True),
        ),
    ]
