# Generated by Django 5.1.5 on 2025-06-03 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0014_remove_processomoagem_eficiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processomoagem',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
