# Generated by Django 5.1.5 on 2025-06-03 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0015_alter_processomoagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculoart',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='processomoagem',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
