# Generated by Django 5.1.5 on 2025-06-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0016_alter_calculoart_data_alter_processomoagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculoart',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
