# Generated by Django 5.1.5 on 2025-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0017_alter_calculoart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvaliquefacao',
            name='produto_gerado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculoart',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
