# Generated by Django 5.1.5 on 2025-06-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0018_curvaliquefacao_produto_gerado_alter_calculoart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoliquefacao',
            name='massa_oligossacarideos',
            field=models.FloatField(help_text='Oligossacarideos gerados (kg)', null=True),
        ),
    ]
