# Generated by Django 5.1.5 on 2025-06-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0019_processoliquefacao_massa_oligossacarideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvaliquefacao',
            name='art',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curvaliquefacao',
            name='oligos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
