# Generated by Django 5.1.5 on 2025-06-05 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0020_curvaliquefacao_art_curvaliquefacao_oligos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoSacarificacaoFermentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_inicial', models.FloatField(help_text='Concentração inicial de ART (g/L) vindo da liquefação')),
                ('oligossacarideos_inicial', models.FloatField(help_text='Concentração inicial de oligossacarídeos (g/L) vindo da liquefação')),
                ('etanol_final', models.FloatField(help_text='Concentração final de etanol (g/L)')),
                ('biomassa_final', models.FloatField(help_text='Concentração final de biomassa celular (g/L)')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('processo_liquefacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacarificacoes', to='simulador.processoliquefacao')),
            ],
        ),
        migrations.CreateModel(
            name='CurvaSacFerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conc_art', models.FloatField(help_text='Concentração de ART (g/L)', null=True)),
                ('conc_oligos', models.FloatField(blank=True, help_text='Concentração de oligossacarídeos (g/L)', null=True)),
                ('conc_etanol', models.FloatField(help_text='Concentração de etanol (g/L)')),
                ('conc_biomassa', models.FloatField(help_text='Concentração de biomassa celular (g/L)')),
                ('tempo_h', models.FloatField(help_text='Tempo (h)')),
                ('processo_sacferm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curva_dados', to='simulador.processosacarificacaofermentacao')),
            ],
        ),
    ]
